const pool = require('./db');
require('dotenv').config();

const products = [
  { name: 'Birthday Celebration Card', category: 'greeting-cards', occasion: 'Birthday', price: 149, tag: 'Bestseller', rating: 4.9, reviews: 234, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80']), description: 'A beautifully designed birthday card with vibrant colors and a personalized message. Printed on premium 350gsm matte paper and delivered in a protective envelope.', includes: JSON.stringify(['Premium 350gsm Card', 'Personalized Message', 'Protective Envelope', 'Free Delivery']), delivery_days: '2-3', keywords: JSON.stringify(['birthday', 'card', 'greetings']) },
  { name: 'Wedding Wishes Card', category: 'greeting-cards', occasion: 'Wedding', price: 199, tag: 'Trending', rating: 4.8, reviews: 178, image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80']), description: 'An elegant wedding card with a classic design. Personalize with the couple\'s names and your heartfelt message.', includes: JSON.stringify(['Luxury Ivory Card', 'Gold Foil Accents', 'Custom Names', 'Envelope']), delivery_days: '2-3', keywords: JSON.stringify(['wedding', 'marriage', 'card']) },
  { name: 'Anniversary Love Card', category: 'greeting-cards', occasion: 'Anniversary', price: 179, tag: 'New', rating: 4.7, reviews: 92, image: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80']), description: 'A romantic anniversary card designed with love. Features a photo slot and a heartfelt message area.', includes: JSON.stringify(['Premium Card', 'Photo Slot', 'Message Area', 'Envelope']), delivery_days: '2-3', keywords: JSON.stringify(['anniversary', 'love', 'card', 'couple']) },
  { name: 'Thank You Card', category: 'greeting-cards', occasion: 'General', price: 99, tag: 'Bestseller', rating: 4.6, reviews: 156, image: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80']), description: 'A simple yet elegant thank you card. Minimalist design with a personalized message.', includes: JSON.stringify(['Minimalist Card', 'Custom Message', 'Envelope', 'Free Delivery']), delivery_days: '2-3', keywords: JSON.stringify(['thank you', 'gratitude', 'card']) },
  { name: 'Luxury Chocolate Hamper', category: 'hampers', occasion: 'Birthday', price: 1299, tag: 'Bestseller', rating: 4.9, reviews: 312, image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80', 'https://images.unsplash.com/photo-1511381939415-e44d9db77f71?w=600&q=80']), description: 'A luxurious hamper filled with premium chocolates. Includes Ferrero Rocher, Lindt, and Cadbury Silk in a beautifully decorated gift box.', includes: JSON.stringify(['Ferrero Rocher (16pcs)', 'Lindt Assorted (200g)', 'Cadbury Silk Heart', 'Premium Gift Box', 'Ribbon & Card']), delivery_days: '3-5', keywords: JSON.stringify(['chocolate', 'hamper', 'birthday', 'sweet']) },
  { name: 'Spa & Wellness Hamper', category: 'hampers', occasion: "Valentine's", price: 1899, tag: 'Trending', rating: 4.8, reviews: 198, image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80']), description: 'A complete spa experience at home. Curated with premium bath and body products.', includes: JSON.stringify(['Lavender Bath Salts', 'Rose Body Lotion', 'Scented Candle', 'Face Mask (3)', 'Loofa & Towel', 'Premium Basket']), delivery_days: '3-5', keywords: JSON.stringify(['spa', 'wellness', 'self care', 'relaxation']) },
  { name: 'Dry Fruits Premium Hamper', category: 'hampers', occasion: 'Festival', price: 1499, tag: 'Bestseller', rating: 4.7, reviews: 267, image: 'https://images.unsplash.com/photo-1604598967049-cca99c0c1e81?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1604598967049-cca99c0c1e81?w=600&q=80']), description: 'A premium dry fruits hamper featuring the finest selection of nuts and dried fruits.', includes: JSON.stringify(['Almonds (250g)', 'Cashews (250g)', 'Pistachios (200g)', 'Walnuts (200g)', 'Decorative Box']), delivery_days: '2-4', keywords: JSON.stringify(['dry fruits', 'nuts', 'festival', 'diwali', 'healthy']) },
  { name: 'Gourmet Tea & Snacks Hamper', category: 'hampers', occasion: 'Birthday', price: 999, tag: 'New', rating: 4.6, reviews: 89, image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600&q=80']), description: 'A delightful tea and snacks hamper for the connoisseur. Features premium teas from around the world.', includes: JSON.stringify(['10 Tea Varieties', 'Artisanal Biscuits', 'Honey Jar (250g)', 'Tea Infuser', 'Ceramic Mug', 'Gift Box']), delivery_days: '3-5', keywords: JSON.stringify(['tea', 'snacks', 'gourmet', 'mug']) },
  { name: 'Baby Shower Hamper', category: 'hampers', occasion: 'Baby Shower', price: 1699, tag: 'Trending', rating: 4.9, reviews: 143, image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80']), description: 'A thoughtfully curated baby shower hamper with essentials for the new arrival.', includes: JSON.stringify(['Baby Onesie (0-3M)', 'Soft Plush Toy', 'Baby Skincare Set', 'Baby Bottle', 'Muslin Cloth (2)', 'Gift Basket']), delivery_days: '3-5', keywords: JSON.stringify(['baby', 'newborn', 'shower', 'infant', 'mom']) },
  { name: 'Corporate Premium Hamper', category: 'hampers', occasion: 'Corporate', price: 2499, tag: 'Bestseller', rating: 4.8, reviews: 76, image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80']), description: 'A sophisticated corporate hamper designed to impress. Available with custom branding.', includes: JSON.stringify(['Premium Diary', 'Metal Pen Set', 'Card Holder', 'Desk Organizer', 'Dry Fruits Box', 'Branded Box']), delivery_days: '3-5', keywords: JSON.stringify(['corporate', 'office', 'business', 'bulk', 'branded']) },
  { name: 'Classic Red Rose Bouquet', category: 'flowers', occasion: "Valentine's", price: 699, tag: 'Bestseller', rating: 4.9, reviews: 456, image: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80']), description: '12 fresh red roses beautifully arranged and tied with a satin ribbon.', includes: JSON.stringify(['12 Fresh Red Roses', "Baby's Breath Fillers", 'Satin Ribbon', 'Greeting Card', 'Water Vial']), delivery_days: '1-2', keywords: JSON.stringify(['roses', 'flowers', 'bouquet', 'red', 'valentine', 'love']) },
  { name: 'Sunflower Sunshine Bouquet', category: 'flowers', occasion: 'Birthday', price: 549, tag: 'Trending', rating: 4.7, reviews: 234, image: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=600&q=80']), description: 'A bright and cheerful bouquet of fresh sunflowers.', includes: JSON.stringify(['8 Fresh Sunflowers', 'Green Fillers', 'Kraft Paper Wrap', 'Twine Bow', 'Greeting Card']), delivery_days: '1-2', keywords: JSON.stringify(['sunflower', 'flowers', 'yellow', 'birthday', 'happy']) },
  { name: 'Mixed Lily Bouquet', category: 'flowers', occasion: 'Anniversary', price: 799, tag: 'New', rating: 4.8, reviews: 167, image: 'https://images.unsplash.com/photo-1490750967868-88df5691cc01?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1490750967868-88df5691cc01?w=600&q=80']), description: 'An elegant mixed lily bouquet featuring pink and white stargazer lilies.', includes: JSON.stringify(['6 Pink Lilies', '4 White Lilies', 'Eucalyptus Fillers', 'Premium Wrap', 'Greeting Card']), delivery_days: '1-2', keywords: JSON.stringify(['lily', 'flowers', 'fragrant', 'anniversary', 'elegant']) },
  { name: 'Rainbow Mixed Bouquet', category: 'flowers', occasion: 'Birthday', price: 899, tag: 'Bestseller', rating: 4.9, reviews: 289, image: 'https://images.unsplash.com/photo-1487530811015-780780a6e0af?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1487530811015-780780a6e0af?w=600&q=80']), description: 'A stunning mix of colorful seasonal flowers arranged by our expert florists.', includes: JSON.stringify(['20 Mixed Flowers', 'Seasonal Fillers', 'Premium Box', 'Greeting Card', 'Free Vase']), delivery_days: '1-2', keywords: JSON.stringify(['mixed', 'colorful', 'flowers', 'bouquet', 'rainbow']) },
  { name: 'Custom Name Necklace', category: 'jewellery', occasion: 'Anniversary', price: 1299, tag: 'Bestseller', rating: 4.9, reviews: 378, image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80']), description: 'A delicate custom name necklace crafted in 925 sterling silver.', includes: JSON.stringify(['925 Sterling Silver', 'Custom Name Engraving', 'Adjustable Chain (16-18")', 'Premium Jewellery Box', 'Certificate of Authenticity']), delivery_days: '4-6', keywords: JSON.stringify(['necklace', 'name', 'jewellery', 'silver', 'personalized', 'custom']) },
  { name: 'Engraved Couple Bracelet Set', category: 'jewellery', occasion: 'Anniversary', price: 1599, tag: 'Trending', rating: 4.8, reviews: 213, image: 'https://images.unsplash.com/photo-1573408301185-9519f94f1f35?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1573408301185-9519f94f1f35?w=600&q=80']), description: 'A matching couple bracelet set with custom engraving.', includes: JSON.stringify(['2 Bracelets (His & Hers)', 'Custom Engraving', 'Premium Gift Box', 'Certificate of Authenticity']), delivery_days: '4-6', keywords: JSON.stringify(['bracelet', 'couple', 'matching', 'engraved', 'jewellery']) },
  { name: 'Birthstone Ring', category: 'jewellery', occasion: "Valentine's", price: 1899, tag: 'New', rating: 4.7, reviews: 124, image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80']), description: 'A beautiful birthstone ring crafted in sterling silver.', includes: JSON.stringify(['925 Sterling Silver Ring', 'Birthstone of Choice', 'Custom Size (4-12)', 'Premium Box']), delivery_days: '5-7', keywords: JSON.stringify(['ring', 'birthstone', 'silver', 'jewellery', 'personalized']) },
  { name: 'Classic Wood Photo Frame', category: 'photo-frames', occasion: 'Anniversary', price: 799, tag: 'Bestseller', rating: 4.8, reviews: 267, image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80']), description: 'A premium solid wood photo frame with elegant finishing.', includes: JSON.stringify(['Solid Wood Frame', 'High-Res Photo Print', 'Custom Engraving Option', 'Glass Cover', 'Hanging Hardware']), delivery_days: '4-6', keywords: JSON.stringify(['photo', 'frame', 'wood', 'picture', 'memory']) },
  { name: 'Acrylic LED Photo Frame', category: 'photo-frames', occasion: 'Birthday', price: 1199, tag: 'Trending', rating: 4.9, reviews: 189, image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&q=80']), description: 'A modern acrylic LED photo frame that illuminates your memories.', includes: JSON.stringify(['Crystal Clear Acrylic', 'Built-in LED Lights', 'USB Powered', 'High-Res Photo Print', 'Remote Control']), delivery_days: '4-6', keywords: JSON.stringify(['photo', 'frame', 'LED', 'acrylic', 'light', 'modern']) },
  { name: 'Collage Photo Frame (9 Photos)', category: 'photo-frames', occasion: 'Birthday', price: 1499, tag: 'New', rating: 4.7, reviews: 134, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80']), description: 'A beautiful collage frame that holds 9 of your favorite memories.', includes: JSON.stringify(['Canvas Collage Print', '9 Photo Slots', 'Premium Frame', 'Hanging Hardware', 'Free Delivery']), delivery_days: '5-7', keywords: JSON.stringify(['collage', 'photo', 'frame', '9 photos', 'canvas', 'memories']) },
  { name: 'Birthday Cake + Rose Bouquet', category: 'cake-flowers', occasion: 'Birthday', price: 1299, tag: 'Bestseller', rating: 4.9, reviews: 389, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80']), description: 'The perfect birthday surprise! A delicious 1kg cake combined with a fresh rose bouquet.', includes: JSON.stringify(['1kg Custom Cake (Flavor Choice)', '6 Red Roses', 'Birthday Candles', 'Greeting Card', 'Same Day Delivery Available']), delivery_days: '1-2', keywords: JSON.stringify(['cake', 'flowers', 'birthday', 'combo', 'celebration']) },
  { name: 'Anniversary Cake + Lilies Combo', category: 'cake-flowers', occasion: 'Anniversary', price: 1599, tag: 'Trending', rating: 4.8, reviews: 234, image: 'https://images.unsplash.com/photo-1490750967868-88df5691cc01?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1490750967868-88df5691cc01?w=600&q=80']), description: 'Celebrate your anniversary in style with a premium heart-shaped cake and fragrant lily bouquet.', includes: JSON.stringify(['1kg Heart-Shaped Cake', '8 Stargazer Lilies', 'Love Candles', 'Personalized Message', 'Premium Packaging']), delivery_days: '1-2', keywords: JSON.stringify(['cake', 'lily', 'anniversary', 'heart', 'combo', 'love']) },
  { name: "Valentine's Day Special Combo", category: 'cake-flowers', occasion: "Valentine's", price: 1899, tag: 'Bestseller', rating: 4.9, reviews: 456, image: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80']), description: "The ultimate Valentine's Day surprise. A romantic red velvet cake paired with stunning roses.", includes: JSON.stringify(['1kg Red Velvet Cake', '12 Red Roses', 'Heart Balloons (2)', 'Love Card', 'Premium Red Box']), delivery_days: '1-2', keywords: JSON.stringify(['valentine', 'cake', 'roses', 'red velvet', 'romantic', 'love']) },
  { name: 'New Year Celebration Combo', category: 'cake-flowers', occasion: 'Festival', price: 1699, tag: 'New', rating: 4.7, reviews: 123, image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=500&q=80', images: JSON.stringify(['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80']), description: 'Celebrate the New Year with a bang! A sparkling themed cake with a beautiful mixed flower bouquet.', includes: JSON.stringify(['1kg New Year Cake', 'Mixed Flower Bouquet', 'Sparklers (4)', 'New Year Card', 'Premium Packaging']), delivery_days: '1-2', keywords: JSON.stringify(['new year', 'cake', 'flowers', 'celebration', 'festival']) },
];

async function seedProducts() {
  try {
    console.log('🌱 Seeding products...');
    const [existing] = await pool.execute('SELECT COUNT(*) as count FROM products');
    if (existing[0].count > 0) {
      console.log('✅ Products already seeded! Skipping...');
      process.exit(0);
    }
    for (const product of products) {
      await pool.execute(
        `INSERT INTO products (name, category, occasion, price, tag, rating, reviews, image, images, description, includes, delivery_days, keywords)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [product.name, product.category, product.occasion, product.price, product.tag, product.rating, product.reviews, product.image, product.images, product.description, product.includes, product.delivery_days, product.keywords]
      );
    }
    console.log(`✅ Successfully seeded ${products.length} products!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error.message);
    process.exit(1);
  }
}

seedProducts();